### ISSUE TITLE
Version ~2.0 could not be found on the Packagist

### ISSUE THREAD

**Issue by hsuhw** [phpDocumentor/Reflection#35] opened 2015-04-21 10:19 UTC
Hi, I found that the newest version on Packagist is 1.0.7. I can't do the `composer require "phpdocumentor/reflection: ~2.0"`.

**Comment by cebe** [comment] 2015-04-21 15:37
2.0 is only a dev version on the dev-develop branch, you have to require it as `dev-develop` as far as I see.

**Comment by hsuhw** [comment] 2015-04-22 05:26
Oh, yes, that's what I ended up to.
I just found the installation instruction in README a bit confusing.

**Comment by jaapio** [comment] 2016-01-03 22:43
You should be able to use 2.0-alpha2 fom packagist.

**Comment by dwsupplee** [comment] 2016-02-03 17:48
Hi @jaapio! I'm having issues installing the alpha. It looks like a required package isn't available on packagist :(. Any recommendations?

Thanks!

Problem 1
    - Installation request for phpdocumentor/reflection 2.0-alpha2 -> satisfiable by phpdocumentor/reflection[2.0.0-alpha2].
    - phpdocumentor/reflection 2.0.0-alpha2 requires phpdocumentor/reflection-common ^1.0@dev -> no matching package found.

**Comment by jaapio** [comment] 2016-02-04 10:02
I think that is caused by the fact that  phpdocumentor/reflection-common  1.0 is still in dev. You can add it to your local composer.json so it will be installed. 

`composer require phpdocumentor/reflection-common:^1.0@dev` 

I will create a new alpha version soon to fix this.

**Comment by jaapio** [comment] 2017-09-07 18:38
We will not release v2. A new version will be tagged when we are finished and happy with the rework.

**Closed by jaapio** 2017-09-07 18:38 UTC
Labels: question
