### ISSUE TITLE
Cannot use ProjectFactory in a PHPUnit test

### ISSUE THREAD

**Issue by dunglas** [phpDocumentor/Reflection#85] opened 2015-11-09 22:00 UTC
This simple test case fail:

``` php
<?php

namespace Dunglas\PhpDocToTypeHint\Tests;

class ConverterTest extends \PHPUnit_Framework_TestCase
{
    public function testConvertFunction()
    {
        \phpDocumentor\Reflection\Php\ProjectFactory::createInstance();
    }
}
```

Here is the stack trace:

```
kdbook:phpdoc-to-type-hint dunglas$ php ../phpunit.phar tests/ConverterTest.php 
PHPUnit 5.0.8 by Sebastian Bergmann and contributors.

PHP Fatal error:  Cannot use phpDocumentor\Reflection\Types\Context as Context because the name is already in use in /Users/dunglas/workspace/phpdoc-to-type-hint/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php on line 18
PHP Stack trace:
PHP   1. {main}() /Users/dunglas/workspace/phpunit.phar:0
PHP   2. PHPUnit_TextUI_Command::main() /Users/dunglas/workspace/phpunit.phar:509
PHP   3. PHPUnit_TextUI_Command->run() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/TextUI/Command.php:105
PHP   4. PHPUnit_TextUI_TestRunner->doRun() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/TextUI/Command.php:154
PHP   5. PHPUnit_Framework_TestSuite->run() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/TextUI/TestRunner.php:425
PHP   6. PHPUnit_Framework_TestCase->run() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/Framework/TestSuite.php:747
PHP   7. PHPUnit_Framework_TestResult->run() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/Framework/TestCase.php:727
PHP   8. PHPUnit_Framework_TestCase->runBare() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/Framework/TestResult.php:617
PHP   9. PHPUnit_Framework_TestCase->runTest() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/Framework/TestCase.php:771
PHP  10. ReflectionMethod->invokeArgs() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/Framework/TestCase.php:908
PHP  11. Dunglas\PhpDocToTypeHint\Tests\ConverterTest->testConvertFunction() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/Framework/TestCase.php:908
PHP  12. phpDocumentor\Reflection\Php\ProjectFactory::createInstance() /Users/dunglas/workspace/phpdoc-to-type-hint/tests/ConverterTest.php:9
PHP  13. phpDocumentor\Reflection\DocBlockFactory::createInstance() /Users/dunglas/workspace/phpdoc-to-type-hint/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/ProjectFactory.php:54
PHP  14. spl_autoload_call() /Users/dunglas/workspace/phpdoc-to-type-hint/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/ProjectFactory.php:52
PHP  15. Composer\Autoload\ClassLoader->loadClass() /Users/dunglas/workspace/phpdoc-to-type-hint/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/ProjectFactory.php:52
PHP  16. Composer\Autoload\includeFile() /Users/dunglas/workspace/phpdoc-to-type-hint/vendor/composer/ClassLoader.php:301

Fatal error: Cannot use phpDocumentor\Reflection\Types\Context as Context because the name is already in use in /Users/dunglas/workspace/phpdoc-to-type-hint/vendor/phpdocumentor/reflection-docblock/src/DocBlock/StandardTagFactory.php on line 18

Call Stack:
    0.0454     645640   1. {main}() /Users/dunglas/workspace/phpunit.phar:0
    0.1077   11601624   2. PHPUnit_TextUI_Command::main() /Users/dunglas/workspace/phpunit.phar:509
    0.1077   11602248   3. PHPUnit_TextUI_Command->run() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/TextUI/Command.php:105
    0.1806   11894472   4. PHPUnit_TextUI_TestRunner->doRun() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/TextUI/Command.php:154
    0.2456   11906392   5. PHPUnit_Framework_TestSuite->run() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/TextUI/TestRunner.php:425
    0.2512   11911736   6. PHPUnit_Framework_TestCase->run() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/Framework/TestSuite.php:747
    0.2512   11913512   7. PHPUnit_Framework_TestResult->run() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/Framework/TestCase.php:727
    0.2513   11916304   8. PHPUnit_Framework_TestCase->runBare() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/Framework/TestResult.php:617
    0.2514   11934944   9. PHPUnit_Framework_TestCase->runTest() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/Framework/TestCase.php:771
    0.2515   11935840  10. ReflectionMethod->invokeArgs() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/Framework/TestCase.php:908
    0.2515   11935904  11. Dunglas\PhpDocToTypeHint\Tests\ConverterTest->testConvertFunction() phar:///Users/dunglas/workspace/phpunit.phar/phpunit/Framework/TestCase.php:908
    0.2762   11981352  12. phpDocumentor\Reflection\Php\ProjectFactory::createInstance() /Users/dunglas/workspace/phpdoc-to-type-hint/tests/ConverterTest.php:9
    0.3310   12635600  13. phpDocumentor\Reflection\DocBlockFactory::createInstance() /Users/dunglas/workspace/phpdoc-to-type-hint/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/ProjectFactory.php:54
    0.3361   12651232  14. spl_autoload_call() /Users/dunglas/workspace/phpdoc-to-type-hint/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/ProjectFactory.php:52
    0.3361   12651304  15. Composer\Autoload\ClassLoader->loadClass() /Users/dunglas/workspace/phpdoc-to-type-hint/vendor/phpdocumentor/reflection/src/phpDocumentor/Reflection/Php/ProjectFactory.php:52
    0.3362   12651496  16. Composer\Autoload\includeFile() /Users/dunglas/workspace/phpdoc-to-type-hint/vendor/composer/ClassLoader.php:301

```

**Comment by jaapio** [comment] 2015-12-02 20:04
Is this still an issue?

Can you provide some more information about this issue? I can't reproduce it in an example project without phpunit.

**Comment by jaapio** [comment] 2017-09-07 18:37
Didn't get the required feedback. Closing now, feel free to reopen when needed.

**Closed by jaapio** 2017-09-07 18:37 UTC

**Comment by dunglas** [comment] 2017-09-07 20:29
Feel free to close, I can't remember how I've fixed that but I've found a workaround back in time.
